### ISSUE TITLE
Metakernel on Windows

### ISSUE THREAD

**Issue by klonuo** [Calysto/octave_kernel#8] opened 2015-03-03 11:56 UTC
Hi,

when I try your module I get this output in console:

```
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\metakernel\pexpect.py", line 67, in <module>
    import pty
  File "c:\python34\lib\pty.py", line 11, in <module>
    import tty
  File "c:\python34\lib\tty.py", line 5, in <module>
    from termios import *
ImportError: No module named 'termios'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python34\lib\site-packages\octave_kernel.py", line 3, in <module>
    from metakernel import MetaKernel, ProcessMetaKernel, REPLWrapper, u
  File "c:\python34\lib\site-packages\metakernel\__init__.py", line 2, in <module>
    from . import pexpect
  File "c:\python34\lib\site-packages\metakernel\pexpect.py", line 76, in <module>
    import Queue
ImportError: No module named 'Queue'
[I 12:41:44.047 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

I'm not into this, but if Metakernel package depends on pexpect, that means derivatives can not be run on Windows. I just browsed some other IPython 3 kernels (like bash) and although it does not depend on Metakernel it uses pexpect, which leads to same result.

Requirement for Python 3 already looks limiting, and if kernels must be build with pexpect then that's a tight hole. I just wish kernel developers state that besides Python 3 user would need *nix, so that we don't get dirty, right ;)

Cheers

**Comment by blink1073** [comment] 2015-03-03 13:47
Hmm, I did test this on Windows at one point.  I'll get it back up to snuff.  Also, it should work on Python 2, just not IPython 2.

**Comment by klonuo** [comment] 2015-03-03 13:57
> Also, it should work on Python 2, just not IPython 2.
Ah, right. Silly me.

**Comment by blink1073** [comment] 2015-03-03 18:15
I just tried it on Windows 7 with Python 2.7, and it works fine.  Perhaps you need a `pip install -U metakernel`.

**Comment by klonuo** [comment] 2015-03-03 18:33
Hm, was running on Windows 7 with Python 3.4...
I tried now with 2.7 and get this:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Python27\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 470, in kernel_info_request
    self.kernel_info, parent, ident)
  File "C:\Python27\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 464, in kernel_info
    'banner': self.banner,
  File "C:\Python27\lib\site-packages\octave_kernel.py", line 38, in banner
    banner = check_output(['octave', '--version'])
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```
Then after trying to execute some Octave code:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Python27\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 362, in execute_request
    user_expressions, allow_stdin)
  File "C:\Python27\lib\site-packages\metakernel\_metakernel.py", line 289, in do_execute
    retval = self.do_execute_direct(code)
  File "C:\Python27\lib\site-packages\octave_kernel.py", line 63, in do_execute_direct
    self.handle_plot_settings()
  File "C:\Python27\lib\site-packages\octave_kernel.py", line 153, in handle_plot_settings
    self.do_execute_direct('\n'.join(cmds))
  File "C:\Python27\lib\site-packages\octave_kernel.py", line 66, in do_execute_direct
    resp = super(OctaveKernel, self).do_execute_direct(code)
  File "C:\Python27\lib\site-packages\metakernel\process_metakernel.py", line 61, in do_execute_direct
    output = self.wrapper.run_command(code.rstrip(), timeout=None)
  File "C:\Python27\lib\site-packages\metakernel\replwrap.py", line 132, in run_command
    self._expect_prompt(timeout=1)
  File "C:\Python27\lib\site-packages\metakernel\replwrap.py", line 99, in _expect_prompt
    timeout=timeout)
  File "C:\Python27\lib\site-packages\metakernel\pexpect.py", line 1646, in expect
    timeout, searchwindowsize, async)
  File "C:\Python27\lib\site-packages\metakernel\pexpect.py", line 1667, in expect_list
    return exp.expect_loop(timeout)
  File "C:\Python27\lib\site-packages\metakernel\pexpect.py", line 229, in expect_loop
    return self.timeout(e)
  File "C:\Python27\lib\site-packages\metakernel\pexpect.py", line 194, in timeout
    raise TIMEOUT(msg)
TIMEOUT: <metakernel.pexpect.spawnu object at 0x026F1E70>
version: 3.3
command: C:\Windows\octave.CMD
args: ['C:\\Windows\\octave.CMD']
searcher: None
buffer (last 100 chars): u'\n'
before (last 100 chars): u'\n'
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 6472
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
<metakernel.pexpect.spawnu object at 0x026F1E70>
version: 3.3
command: C:\Windows\octave.CMD
args: ['C:\\Windows\\octave.CMD']
searcher: None
buffer (last 100 chars): u'\n'
before (last 100 chars): u'\n'
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 6472
child_fd: 6
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
[I 19:28:10.875 NotebookApp] Interrupted...
[I 19:28:10.875 NotebookApp] Shutting down kernels
[I 19:28:11.079 NotebookApp] Kernel shutdown: 371912df-e064-4678-8921-86c8951cbe3e
```

Any ideas, what I may did wrong?

**Comment by blink1073** [comment] 2015-03-03 18:37
What is `C:\Windows\octave.CMD`?  It looks like `metakernel.pexpect` is finding that instead of `octave.exe` in this [function](https://github.com/Calysto/metakernel/blob/master/metakernel/pexpect.py#L2177).

**Comment by klonuo** [comment] 2015-03-03 18:41
@blink1073, I just updated by removing octave.cmd from path as I thought also that it may be the problem, but still the same. Please look again in previous post.

`octave.cmd` was just a wrapper to octave binary without adding octave folder in path, but as mentioned I changed that now and receive same message for some reason

**Comment by franktoffel** [comment] 2015-03-03 20:39
Should I install Python 2 or this works with Python 3?

I was trying this unsuccessfully and I have got the following problems on Windows 67 with Python 3 (anaconda).

First it was a problem with Queue, but I modified the pexpect.py changing Queue to queue 

I have also a binary and I added the PATH properly (executing `octave` on cmd starts an Octave console).

I am still having issues with Py3 I guess (besides Queue), right now I have this one:


--> 312         data = self.buffer + input
        data = undefined
        self.buffer = b''
        input = ''
    313         (result, consumed) = self._buffer_decode(data, self.errors, fina
l)
    314         # keep undecoded input until the next call

TypeError: can't concat bytes to str

**Comment by blink1073** [comment] 2015-03-03 21:17
My mistake, I was using an older version of `octave_kernel` earlier.  I can confirm both of your errors, and will try and figure out a solution.

**Comment by blink1073** [comment] 2015-03-04 04:31
The latest releases of `metakernel` and `octave_kernel` *should* handle these errors.

**Comment by klonuo** [comment] 2015-03-04 13:21
Thanks @blink1073

After updating both modules, I tested with both Python2 and Python 3 and it works as expected :)

Cheers

**Comment by blink1073** [comment] 2015-03-04 13:35
Great @klonuo, glad to help.

**Comment by blink1073** [comment] 2015-03-04 13:36
@franktoffel, care to try again?

**Comment by franktoffel** [comment] 2015-03-04 14:24
@blink1073, sure! I will try it later today or tomorrow and let you know :)

**Comment by franktoffel** [comment] 2015-03-04 22:29
@blink1073 ok, now the installation worked with Python 3 :+1: 

However, I get this error when trying to plot any figure (normal commands work just fine)


```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1245, in _send
    return os.write(self.write_fd, s)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\process_metakernel.py", line 61, in do_execute_direct
    output = self.wrapper.run_command(code.rstrip(), timeout=None)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\replwrap.py", line 134, in run_command
    self._expect_prompt(timeout=-1)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\replwrap.py", line 97, in _expect_prompt
    self.sendline(self.prompt_emit_cmd)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\replwrap.py", line 87, in sendline
    self.child.sendline(line)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1257, in sendline
    n = n + self.send(self.linesep)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1236, in send
    return self._send(s)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1939, in _send
    return super(spawnu, self)._send(s.encode(self.encoding, self.errors))
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1248, in _send
    raise EOF('Attempted write to a closed file descriptor')
metakernel.pexpect.EOF: Attempted write to a closed file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\franz\Anaconda3\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\franz\Anaconda3\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 362, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\_metakernel.py", line 312, in do_execute
    retval = self.do_execute_direct(code)
  File "C:\Users\franz\Desktop\octave_kernel-master\octave_kernel.py", line 69, in do_execute_direct
    resp = super(OctaveKernel, self).do_execute_direct(code)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\process_metakernel.py", line 69, in do_execute_direct
    self._start()
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\process_metakernel.py", line 46, in _start
    self.wrapper.child.terminate()
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1326, in terminate
    self.kill(signal.SIGTERM)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1498, in kill
    os.kill(self.pid, sig)
PermissionError: [WinError 5] Access is denied
```
Looks like I messed up with the installation of metakernel. I'll open a ticket there ;)

**Comment by blink1073** [comment] 2015-03-06 02:25
@franktoffel, what is the full output of:   `octave --eval "available_graphics_toolkits"` from cmd.exe?

**Comment by franktoffel** [comment] 2015-03-09 18:34
Sorry for the delay, here it comes:

GNU Octave, version 3.8.2
Copyright (C) 2014 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "i686-w64-mingw32".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

ans =
{
  [1,1] = fltk
  [1,2] = gnuplot
}

**Comment by blink1073** [comment] 2015-03-09 22:35
Hmm, perhaps `pip install --upgrade metakernel`

**Comment by franktoffel** [comment] 2015-03-10 11:40
I have uninstalled metakernel via pip and tried again by setup.py from source. Again, I have troubles when trying to plot. These are generated when trying to use the qtconsole (not the notebook):

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 223, in expect_loop
    return self.timeout()
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 197, in timeout
    raise TIMEOUT(msg)
metakernel.pexpect.TIMEOUT: <metakernel.pexpect.spawnu object at 0x000000000434D320>
version: 3.3
command: C:\Program Files\octave-3.8.2\bin\octave.EXE
args: ['C:\\Program Files\\octave-3.8.2\\bin\\octave.EXE']
searcher: None
buffer (last 100 chars): '\n'
before (last 100 chars): '\n'
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 6152
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\franz\Anaconda3\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\franz\Anaconda3\lib\site-packages\IPython\kernel\zmq\kernelbase.py", line 362, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\_metakernel.py", line 312, in do_execute
    retval = self.do_execute_direct(code)
  File "C:\Users\franz\Anaconda3\lib\site-packages\octave_kernel.py", line 69, in do_execute_direct
    resp = super(OctaveKernel, self).do_execute_direct(code)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\process_metakernel.py", line 61, in do_execute_direct
    output = self.wrapper.run_command(code.rstrip(), timeout=None)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\replwrap.py", line 138, in run_command
    if self._expect_prompt(timeout=timeout) == 1:
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\replwrap.py", line 101, in _expect_prompt
    timeout=timeout)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1649, in expect
    timeout, searchwindowsize, async)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1670, in expect_list
    return exp.expect_loop(timeout)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 232, in expect_loop
    return self.timeout(e)
  File "C:\Users\franz\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 197, in timeout
    raise TIMEOUT(msg)
metakernel.pexpect.TIMEOUT: <metakernel.pexpect.spawnu object at 0x000000000434D320>
version: 3.3
command: C:\Program Files\octave-3.8.2\bin\octave.EXE
args: ['C:\\Program Files\\octave-3.8.2\\bin\\octave.EXE']
searcher: None
buffer (last 100 chars): '\n'
before (last 100 chars): '\n'
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 6152
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
<metakernel.pexpect.spawnu object at 0x000000000434D320>
version: 3.3
command: C:\Program Files\octave-3.8.2\bin\octave.EXE
args: ['C:\\Program Files\\octave-3.8.2\\bin\\octave.EXE']
searcher: None
buffer (last 100 chars): '\n'
before (last 100 chars): '\n'
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 6152
child_fd: 7
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
```

Hope it helps

**Comment by blink1073** [comment] 2015-03-14 20:35
@franktoffel, I'm a bit at a loss.  I tried with `metakernel 0.9.0`, the master branch of `octave_kernel`, `IPython 3.0.0`, `Octave 3.8.2`, Windows 7, Python 3.4.1 Anaconda.  I am able to plot just fine using the QtConsole.

**Comment by deanlxvii** [comment] 2015-06-19 11:10
I think this issue transcends operating systems.

I am using Linux Mint 17.1 Cinnamon ,  Python 2.7.6, `metakernel (0.9.0)`, `oct2py (3.2.0)`, `octave-kernel (0.10.0)`, GNU Octave, version 3.8.1. 
Using just octave (in a notebook ) seems to work but when trying to plot something I get pretty much the same errors as @franktoffel.

```
 [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/IPython/kernel/zmq/kernelbase.py", line 213, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/IPython/kernel/zmq/kernelbase.py", line 362, in execute_request
    user_expressions, allow_stdin)
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/metakernel/_metakernel.py", line 312, in do_execute
    retval = self.do_execute_direct(code)
  File "/home/dean/.home/opt/jupyter/lib/python2.7/site-packages/octave_kernel.py", line 76, in do_execute_direct
    self._make_figs(plot_dir)
  File "/home/dean/.home/opt/jupyter/lib/python2.7/site-packages/octave_kernel.py", line 154, in _make_figs
    super(OctaveKernel, self).do_execute_direct(cmd.replace('\n', ''))
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/metakernel/process_metakernel.py", line 61, in do_execute_direct
    output = self.wrapper.run_command(code.rstrip(), timeout=None)
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/metakernel/replwrap.py", line 138, in run_command
    if self._expect_prompt(timeout=timeout) == 1:
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/metakernel/replwrap.py", line 101, in _expect_prompt
    timeout=timeout)
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/metakernel/pexpect.py", line 1649, in expect
    timeout, searchwindowsize, async)
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/metakernel/pexpect.py", line 1670, in expect_list
    return exp.expect_loop(timeout)
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/metakernel/pexpect.py", line 232, in expect_loop
    return self.timeout(e)
  File "/home/dean/.home/opt/jupyter/local/lib/python2.7/site-packages/metakernel/pexpect.py", line 197, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<metakernel.pexpect.spawnu object at 0x7f3231f0a1d0>
version: 3.3
command: /usr/bin/octave
args: ['/usr/bin/octave']
searcher: None
buffer (last 100 chars): u't line 423, column 14\r\nerror:   /usr/share/octave/3.8.1/m/plot/util/saveas.m at line 105, column 3\r\n'
before (last 100 chars): u't line 423, column 14\r\nerror:   /usr/share/octave/3.8.1/m/plot/util/saveas.m at line 105, column 3\r\n'
after: <class 'metakernel.pexpect.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 7149
child_fd: 41
closed: False
timeout: 30
delimiter: <class 'metakernel.pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
```

**Comment by blink1073** [comment] 2015-06-19 12:11
@deanlxvii, can you try with `%plot -f svg` and `%plot -f png` to see if that makes a difference?

**Comment by deanlxvii** [comment] 2015-06-19 23:03
Alas, tried both in cell
```
t = linspace(0,6*pi,100);
plot(sin(t))
grid on
hold on
plot(cos(t), 'r')
```

both resulting in the same error as above.

**Comment by blink1073** [comment] 2015-06-20 11:16
@deanlxvii, do you have an `.octaverc` file on your system?

**Comment by deanlxvii** [comment] 2015-06-20 16:14
No I don't have an  `.octaverc` in my `~`. There are however two (default?) `octaverc` files in the `octave_home` dir.

**Comment by blink1073** [comment] 2015-06-20 17:06
Can you paste the contents of those files?



—

**Comment by deanlxvii** [comment] 2015-06-20 17:41
Not much in this one `/usr/share/octave/site/m/startup/octaverc`
```
## System-wide startup file for Octave.
##
## This file should contain any commands that should be executed each
## time Octave starts for every user at this site.
```
More in this one `/usr/share/octave/3.8.1/m/startup/octaverc` , which is a symbolic link to `/etc/octave.cfg`
```
### System-wide startup file for Octave.
###
### This file should contain any commands that should be executed each
### time Octave starts for every user at this site.

## This file is an extended copy of Octave's startup file at
## /usr/share/octave/${OCTAVE_VERSION}/m/startup/octaverc
## Configure readline using the file inputrc in the Octave startup
## directory.

readline_read_init_file (sprintf ("%s%s%s",
                                  octave_config_info ("startupfiledir"),
                                  filesep, "inputrc"));

if (strcmp (PAGER (), "less") && isempty (getenv ("LESS")))
  PAGER_FLAGS ('-e -X -P"-- less ?pB(%pB\\%):--. (f)orward, (b)ack, (q)uit$"');
endif

## This appears here instead of in the pkg/PKG_ADD file so that --norc
## will also skip automatic loading of packages.

pkg ("load", "auto");

atexit ("__finish__");

## Set the Debian-specific error handler

missing_component_hook ("debian_missing_handler");
```

**Comment by blink1073** [comment] 2015-06-21 22:16
Hmm, I can't see anything that might cause your problem.  I'm afraid I'm out of ideas at the moment.

**Comment by deanlxvii** [comment] 2015-06-22 08:41
Ok, thanks for your time. 

I suspect some installation has gone wrong somewhere *on my end*.  I've got another (older) *working* installation running on a `Ubuntu 14.04`, which I kept up to date, so it has the same versions of almost all packages. So I tried to a fresh installation on the `Mint` in a `virtualenv` with the packages I had on the `Ubuntu` but is resulted in the same errors.

While installing/deleting `octave_kernel` in "desperation" with `pip` I observed something, which probably deserves it's own issue, if it can be confirmed. When I installed `octave_kernel`  with `pip 6.1.1` it created in the `.ipython/` dir `kernels/octave_kernel/kernel.json`. Installing `octave_kernel` with the latest `pip 7.0.3` did not create anything in the `.ipython/` dir.

**Comment by deanlxvii** [comment] 2015-06-24 08:45
**Solved**, at least at my end.

Not an installation gone wrong, but an installation not *done*. It needed `gnuplot-x11`.
Trying to  plot by  using `%octave` magic from `oct2py` gave the solution, by giving this warning:

```
UserWarning: Oct2Py may not be able to display plots properly without gnuplot, please install it (gnuplot-x11 on Linux)
```

BTW: I ran `octave --eval "available_graphics_toolkits` too, before installing `gnuplot-x11` I got the same output as @franktoffel 


```
....
....
ans =
{
  [1,1] = fltk
  [1,2] = gnuplot
}
```
Does this mean that there is a toolkit `gnuplot` in `octave` that interacts with `gnuplot`, the application, if there is one ?

**Comment by blink1073** [comment] 2015-06-24 11:20
Interesting @deanlxvii, my hunch is that `octave` listed support for `gnuplot` even though the `gnuplot` application was not installed.  The output you are seeing above is checking for the existence of `gnuplot` as a standalone program.  I'll see if I can get this warning to display in the Octave Kernel session.

**Comment by blink1073** [comment] 2015-06-25 02:33
I just released v0.11, which should address this problem.

**Comment by blink1073** [comment] 2015-06-25 03:00
@deanlxvii, as to your pip concern, it looks like the location has changed in IPython.  For me it is `/usr/local/share/jupyter/kernels/octave_kernel` on OSX.

**Comment by dsblank** [comment] 2015-11-09 23:35
Can we close this issue?

**Comment by blink1073** [comment] 2015-11-20 18:50
Closing due to lack of response, feel free to reopen.

**Closed by blink1073** 2015-11-20 18:50 UTC
