### ISSUE TITLE
having to press enter twice for each statement

### ISSUE THREAD

**Issue by achilyz** [Calysto/octave_kernel#95] opened 2017-08-07 09:21 UTC
```
➜  ~ jupyter console --kernel octave
Jupyter console 5.1.0

Octave Kernel v0.26.2 running GNU Octave v4.2.1


In [1]: a = [1 2 3];
      : 

In [2]: 
```

**Comment by dsblank** [comment] 2017-08-07 10:52
Actually, the problem is that you have to enter a blank line at the end to signal that this is the end of the cell. Perhaps there is a Octave function that can tell if the expression is complete? Each metakernel language can override kernel.do_is_complete() to return "complete". Then it would work like, say, ipython.

**Comment by blink1073** [comment] 2017-08-07 12:21
I don't know of a way to ask Octave whether a block of code is complete.  The Matlab kernel uses the [pcode](https://github.com/Calysto/matlab_kernel/blob/3755cb29ead4bf0acf9dd3c5989f608c3fe44a82/matlab_kernel/kernel.py#L173) function for this, but it is not implemented in Octave:

```
octave:1> pcode
warning: the 'pcode' function is not yet implemented in Octave

Please read <http://www.octave.org/missing.html> to learn how you can
contribute missing functionality.
warning: called from
    __unimplemented__ at line 524 column 5
error: 'pcode' undefined near line 1 column 1
```

**Comment by dsblank** [comment] 2017-11-14 22:05
Closing, as this is how the kernel works.

**Closed by dsblank** 2017-11-14 22:05 UTC
