### ISSUE TITLE
`__stdin_prompt>` shows up in some output lines

### ISSUE THREAD

**Issue by profbrady** [Calysto/octave_kernel#69] opened 2017-01-20 15:10 UTC
I am using Octave via a Jupyter notebook in SageMathCloud (SMC) for a bunch of assignments this semester. Today was the first day doing so with my class. Myself and many students are getting an occasional glitch as the last line in some output cells: `__stdin_prompt>`

If the code is re-executed, the glitch usually disappears, but not always.

Is there possibly something I can do or is it due to the Octave kernel. I had never run across this while creating assignments a few weeks ago or using Octave kernel via Jupyter last year for this class. I was not using SMC last year, BTW.

**Comment by blink1073** [comment] 2017-01-20 16:41
Ah, I added the ability to use `input()` and friends, which required forcing `Octave` to send that prompt.  It is supposed to be stripped from the output.  I'll take a look this weekend.

**Comment by blink1073** [comment] 2017-01-20 16:45
Do you know happen to know which version of Octave Kernel it is (see #70 for why this isn't as easy as it should be).  The current is `v0.23.2`.

**Comment by blink1073** [comment] 2017-01-21 14:26
I played with the kernel on SMC and was unable to reproduce the stdin prompt showing.  Do you have some representative code that triggers it?

**Comment by profbrady** [comment] 2017-01-23 19:45
Nothing in particular seemed to cause it. It just randomly happened. I graded 54 assignments with 30+ input lines each and ran across it maybe 20 times.

----------------
Brian Brady

On January 21, 2017 at 9:26:36 AM, Steven Silvester (notifications@github.com) wrote:

I played with the kernel on SMC and was unable to reproduce the stdin prompt showing. Do you have some representative code that triggers it?

**Comment by blink1073** [comment] 2017-01-23 19:46
If you come across it again I'd greatly appreciate a reproducible example.

**Comment by profbrady** [comment] 2017-01-24 01:43
Here is a notebook I just went thru with my students. I made a duplicate and started running the code cells. At In[27] you’ll see that I got the `__stdin_prompt>` glitch.

https://cloud.sagemath.com/projects/234d30f7-3457-42bb-ba8c-d82aef9df333/files/MECH%20322%20Spring%202017%20Assignments/Lab%2004/Lab%2004%20Octave%20Intro%20-%20Sample.html

----------------
Brian Brady

On January 23, 2017 at 2:46:23 PM, Steven Silvester (notifications@github.com) wrote:

If you come across it again I'd greatly appreciate a reproducible example.

**Comment by profbrady** [comment] 2017-01-24 01:46
The same notebook has the glitch at a couple of other code cells further down as well.

----------------
Brian Brady

On January 23, 2017 at 8:43:37 PM, Brian Brady (briandbrady@mac.com) wrote:

Here is a notebook I just went thru with my students. I made a duplicate and started running the code cells. At In[27] you’ll see that I got the `__stdin_prompt>` glitch.

https://cloud.sagemath.com/projects/234d30f7-3457-42bb-ba8c-d82aef9df333/files/MECH%20322%20Spring%202017%20Assignments/Lab%2004/Lab%2004%20Octave%20Intro%20-%20Sample.html

----------------
Brian Brady

On January 23, 2017 at 2:46:23 PM, Steven Silvester (notifications@github.com) wrote:

If you come across it again I'd greatly appreciate a reproducible example.

**Comment by profbrady** [comment] 2017-01-24 01:52
The link I attached was for the html version, here is the ipynb version.

https://cloud.sagemath.com/projects/234d30f7-3457-42bb-ba8c-d82aef9df333/files/MECH%20322%20Spring%202017%20Assignments/Lab%2004/Lab%2004%20Octave%20Intro%20-%20Sample.ipynb

----------------
Brian Brady

On January 23, 2017 at 8:46:17 PM, Brian Brady (briandbrady@mac.com) wrote:

The same notebook has the glitch at a couple of other code cells further down as well.

----------------
Brian Brady

On January 23, 2017 at 8:43:37 PM, Brian Brady (briandbrady@mac.com) wrote:

Here is a notebook I just went thru with my students. I made a duplicate and started running the code cells. At In[27] you’ll see that I got the `__stdin_prompt>` glitch.

https://cloud.sagemath.com/projects/234d30f7-3457-42bb-ba8c-d82aef9df333/files/MECH%20322%20Spring%202017%20Assignments/Lab%2004/Lab%2004%20Octave%20Intro%20-%20Sample.html

----------------
Brian Brady

On January 23, 2017 at 2:46:23 PM, Steven Silvester (notifications@github.com) wrote:

If you come across it again I'd greatly appreciate a reproducible example.

**Comment by blink1073** [comment] 2017-01-24 02:13
Excellent, thank you!

**Comment by blink1073** [comment] 2017-01-24 11:57
I was able to reproduce only once, but from available evidence it looks like it was always occurring on lines after the first.  Version 0.24.5 should clear this up, cf f07fb99.

**Comment by blink1073** [comment] 2017-01-24 12:01
I submitted a ticket to SMC asking for an update to the installed kernel version.

**Comment by blink1073** [comment] 2017-01-24 12:01
cf https://sagemathcloud.zendesk.com/requests/2741.

**Comment by blink1073** [comment] 2017-02-26 22:00
This was fixed by #66.

**Closed by blink1073** 2017-02-26 22:00 UTC
